# 1. Usamos una imagen de Python optimizada
FROM python:3.9-slim

# 2. Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# 3. Instalar dependencias del sistema para OpenCV
# Se usa libgl1 en lugar del antiguo libgl1-mesa-glx para evitar errores de paquetes obsoletos
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# 4. Copiar el archivo de requerimientos primero para aprovechar la caché de Docker
COPY requirements.txt .

# 5. Instalar las librerías de Python
RUN pip install --no-cache-dir -r requirements.txt

# 6. Copiar todo el contenido de tu proyecto al contenedor
COPY . .

# Exponer el puerto
EXPOSE 5002

# COMANDO DE INICIO (Usamos Gunicorn en vez de python app.py)
# 4 workers permite atender 4 peticiones a la vez
CMD ["python", "deteccion.py"]